"""Change started_at default to app-side UTC

Revision ID: 40995412eaed
Revises: 20240506_0001
Create Date: 2025-11-05 02:20:21.980063

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '40995412eaed'
down_revision = '20240506_0001'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_metric_samples_ts'), table_name='metric_samples')
    op.drop_index(op.f('ix_test_runs_started_at'), table_name='test_runs')
    op.create_index(op.f('ix_test_runs_id'), 'test_runs', ['id'], unique=False)
    op.drop_column('test_runs', 'started_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('test_runs', sa.Column('started_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text("timezone('utc'::text, now())"), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_test_runs_id'), table_name='test_runs')
    op.create_index(op.f('ix_test_runs_started_at'), 'test_runs', ['started_at'], unique=False)
    op.create_index(op.f('ix_metric_samples_ts'), 'metric_samples', ['ts'], unique=False)
    # ### end Alembic commands ###
