"""Change started_at default to app-side UTC

Revision ID: 5a83dd831d49
Revises: 40995412eaed
Create Date: 2025-11-05 02:24:41.240060

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5a83dd831d49'
down_revision = '40995412eaed'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('test_runs', sa.Column('started_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('test_runs', 'started_at')
    # ### end Alembic commands ###
